# More information: https://github.com/NobelD/NobleWhitelist/wiki
# TODO modify and messages grammar
discord:
  # The token of your bot, be sure to not share it with anyone!
  bot-token: ""
  # The server id for the bot.
  server-id: ""
# A list of user defined channels, consists of a custom name and the channel id, this does not require the same name of the channel
# You can add more channels as you want, keep in mind channel ids are dynamically reloaded, but new channel entries requires restarting the server.
# Other sections may require you to provide a channel name, these are defined here.
channel:
  primary: 0000000000000000000
  staff: 0000000000000000000
special:
  # Makes the commands only visible for users who have the server manage permission.
  # If disabled all the users can see the commands and description (but they are still not allowed to execute it without the necessary roles)
  admin-only-server-manage: true
  # Allows the bot to automatically give a custom role to a newly registered user.
  give-role-on-register: false
  # Allows the bot to automatically remove the whitelisted role from an unregistered user.
  remove-role-on-unregister: false
role:
  # Enables the use of "everyone" as a role name to pass any user.
  enable-everyone-role: false
  # A fixed list of role ids, consist of a sub list of roles for each role name.
  # You can modify, add or remove the ids, and they will be dynamically reloaded, but the roles name are fixed.
  # Other sections may require you to provide a role, these are the only available (and everyone role if enabled)
  user:
    - 0000000000000000000
    - 0000000000000000000
  staff:
    - 0000000000000000000
  admin:
    - 0000000000000000000
    - 0000000000000000000
  # The main whitelisted role to add to the users if it is enabled.
  whitelisted: 0000000000000000000
  # Extra roles to be added along the main whitelist role, these roles are not enforced to the user, and it may not be added in some rare cases.
  sub-whitelisted:
    - 0000000000000000000
# Channels to announce certain actions, you need to put a channel name defined in this file.
# You can use "none" to disable each announce message.
announce-channel:
  # When the server starts.
  start: none
  # When the server stops.
  stop: none
  # When a user is registered by the register command.
  notify-self-register: staff
  # When a user is removed by the unregister command.
  notify-self-remove: staff
  # When a user has a role added.
  notify-role-add: none
  # When a user has a role removed.
  notify-role-remove: none
  # If auto register enabled, when a player was automatically added to the whitelist.
  notify-wl-auto: none
  # When a player is allowed to join if the whitelist is enabled.
  notify-wl-join: none
  # When a player is denied to join if the whitelist is enabled.
  notify-wl-try: none
# Defines the command behaviour.
# Only users with the roles will be allowed to execute the commands.
# Commands will only work in the specified channels.
command:
  #/whitelist add
  basic-add-self:
    role:
      - user
      - staff
      - admin
    channel:
      - primary
      - staff
  #/whitelist remove
  basic-remove-self:
    role:
      - user
      - staff
      - admin
    channel:
      - primary
      - staff
  #/whitelist link
  basic-link-self:
    role:
      - admin
    channel:
      - staff
  #/whitelist accounts
  basic-self-accounts:
    role:
      - user
      - staff
      - admin
    channel:
      - primary
      - staff
  #/wladmin add
  admin-add:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin remove
  admin-remove:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin on
  admin-on:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin off
  admin-off:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin permstatus
  admin-perm-status:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin permset
  admin-perm-set:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin checkstatus
  admin-checking-status:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin checkset
  admin-checking-set:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin list
  admin-list:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin find
  admin-find:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin user
  admin-find-user:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin link
  admin-user-link:
    role:
      - admin
    channel:
      - staff
  #/wladmin unlink
  admin-user-unlink:
    role:
      - admin
    channel:
      - staff
  #/wladmin toggle
  admin-user-toggle:
    role:
      - staff
      - admin
    channel:
      - staff
version:
  # Notify when there is a new update.
  notify-update: true
  # DO NOT MODIFY, THIS MAY FORCE CHANGES AND CREATE ERRORS
  version: 2