# More information: https://github.com/NobelD/NobleWhitelist/wiki
discord:
  bot-token: ""
  server-id: ""
# You can add more channels later with their respective id.
# While the channels id can be dynamically changed, the channel itself needs to restart the plugin to be reloaded.
channel:
  primary: 0000000000000000000
  staff: 0000000000000000000
special:
  # Makes the commands only visible for users who have the server manage permission.
  # If disabled all the users can see the commands and description (still can't be used without the necessary role)
  # Restart the server to apply changes.
  admin-only-server-manage: true
  # Gives the roles to the whitelisted user.
  give-role-on-register: false
  # Removes the roles from the user if unregisters.
  remove-role-on-unregister: false
role:
  # Add the option to use "everyone" as role, this allows to the command be executed by everyone even if it does not have roles.
  enable-everyone-role: false
  # The roles cannot be added more as channels, these are fixed.
  # But you can still change it without reloading.
  user:
    - 0000000000000000000
    - 0000000000000000000
  staff:
    - 0000000000000000000
  admin:
    - 0000000000000000000
    - 0000000000000000000
  # This role will be given to the user when registers and will be used to check if the user has the whitelist role.
  whitelisted: 0000000000000000000
  # This extra roles will be given when the whitelist role is given and are not checked.
  sub-whitelisted:
    - 0000000000000000000
announce-channel:
  start: none
  stop: none
  notify-self-register: staff
  notify-self-remove: staff
  notify-role-add: none
  notify-role-remove: none
  notify-wl-auto: none
  notify-wl-join: none
  notify-wl-try: none
command:
  #/whitelist add
  basic-add-self:
    role:
      - user
      - staff
      - admin
    channel:
      - primary
      - staff
  #/whitelist remove
  basic-remove-self:
    role:
      - user
      - staff
      - admin
    channel:
      - primary
      - staff
  #/whitelist link
  basic-link-self:
    role:
      - admin
    channel:
      - staff
  #/whitelist accounts
  basic-self-accounts:
    role:
      - user
      - staff
      - admin
    channel:
      - primary
      - staff
  #/wladmin add
  admin-add:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin remove
  admin-remove:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin on
  admin-on:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin off
  admin-off:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin permstatus
  admin-perm-status:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin permset
  admin-perm-set:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin checkstatus
  admin-checking-status:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin checkset
  admin-checking-set:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin list
  admin-list:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin find
  admin-find:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin user
  admin-find-user:
    role:
      - staff
      - admin
    channel:
      - staff
  #/wladmin link
  admin-user-link:
    role:
      - admin
    channel:
      - staff
  #/wladmin unlink
  admin-user-unlink:
    role:
      - admin
    channel:
      - staff
  #/wladmin toggle
  admin-user-toggle:
    role:
      - staff
      - admin
    channel:
      - staff
version:
  # Notify when there is a new update.
  notify-update: true
  version: 2