name: NWLDiscord
version: $version
main: me.nobeld.noblewhitelist.discord.NWLDiscord
description: $description
author: NobelD
website: https://github.com/NobelD/NobleWhitelist
api-version: $paperApiVersion
folia-supported: true
dependencies:
  server:
    NobleWhitelist:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  noblewhitelist.discord:
    description: "Permission to manage the plugin"
    default: op