# All the config will dynamically be changed, is not necessary to reload the config.
# The Whitelist config is read only, if you change data is necessary make a reload.
# Prefer to use the commands before editing the Whitelist config.
whitelist:
  # Alternate the whitelist, will dynamically be changed.
  enabled: false
  # Will disable the name change in the whitelist config if the player joins with the same uuid but different name.
  # If you have a low performance server this can help a little.
  skip-name-change: false
  # Posible values for checking:
  # disabled: will not be used when checking.
  # optional: will be an option when checking.
  # required: will be necessary for the player
  # if all disabled then the whitelist will not block players even if its enabled.
  # The bypass permission is "noblewhitelist.bypass" or had op.
  # If name and uuid are required will not allow to add players with the command if both the name and uuid are not specified.
  checking:
    name: "optional"
    uuid: "optional"
    perm: "disabled"
  # If enabled and the whitelist is disabled then will auto register the name and uuid of the player.
  # Useful if you want to enable the whitelist time later and keep the players who joined in the whitelist.
  auto-register: false
  # This will block if a player joins with the same name as another registered player but with a different uuid.
  # If you have a server with online and offline uuid players at the same time, ensure that the online player is well registered.
  enforce-uuid-if-different-name: true
messages:
  prefix: "<bold><#17B90C>N<#7FD024>Whitelist</bold> <grey>>"
  use-prefix: true
  # Placeholders:
  # <player> = Player name
  # <prefix> = Message prefix (if disabled will not be showed)
  not-whitelisted: "<red>You are not whitelisted on this server."
  # This message will be sent to the console when a player joins with the same uuid but different name.
  name-change-console: "<prefix><yellow><name> has joined with another name (probably a premium player)"
  name-change-player: "<green>Successfully validated uuid, welcome back <name>!"
version:
  # Notify when there is a new update.
  notify-update: true