name: NobleWhitelist
version: $version
main: me.nobeld.noblewhitelist.NobleWhitelist
description: $description
api-version: '$apiVersion'
dependencies:
  server:
    NWLDiscord:
      load: AFTER
      required: false
      join-classpath: true